import Ajv, { JSONSchemaType } from "ajv";
import { 
  Abilities,
} from "../../domain";

export const abilitiesSchema: JSONSchemaType<Abilities> = {
  type: "object",
  properties: {
    "alertness":       {type: "number"},
    "athletics":       {type: "number"},
    "brawl":       {type: "number"},
    "empathy":       {type: "number"},
    "expression":       {type: "number"},
    "intimidation":       {type: "number"},
    "leadership":       {type: "number"},
    "streetwise":       {type: "number"},
    "subterfuge":       {type: "number"},
    "awareness":       {type: "number"},
    "animalken":       {type: "number"},
    "crafts":       {type: "number"},
    "drive":       {type: "number"},
    "etiquette":       {type: "number"},
    "firearms":       {type: "number"},
    "melee":       {type: "number"},
    "performance":       {type: "number"},
    "stealth":       {type: "number"},
    "survival":       {type: "number"},
    "larceny":       {type: "number"},
    "academics":       {type: "number"},
    "computer":       {type: "number"},
    "finance":       {type: "number"},
    "investigation":       {type: "number"},
    "law":       {type: "number"},
    "medicine":       {type: "number"},
    "occult":       {type: "number"},
    "politics":       {type: "number"},
    "science":       {type: "number"},
    "technology":       {type: "number"},
  },
  required: [
    "alertness",
    "athletics",
    "brawl",
    "empathy",
    "expression",
    "intimidation",
    "leadership",
    "streetwise",
    "subterfuge",
    "awareness",
    "animalken",
    "crafts",
    "drive",
    "etiquette",
    "firearms",
    "melee",
    "performance",
    "stealth",
    "survival",
    "larceny",
    "academics",
    "computer",
    "finance",
    "investigation",
    "law",
    "medicine",
    "occult",
    "politics",
    "science",
    "technology",
  ],
  additionalProperties: false,
};