import Ajv, { JSONSchemaType } from "ajv";
import { CharSheetData } from "./types";
import {
  attributesSchema,
  backgroundsSchema,
  disciplinesSchema,
  flawsSchema,
  meritsSchema,
  notesSchema,
  profileSchema,
  stateSchema,
  healthSchema,
  virtuesSchema,
  artsSchema,
  realmsSchema,
  presetSchema,
} from "./validateCharSheetDataElements";
import {
  abilitiesSchema,
  abilitiesExtensionSchema,
} from "./abilitiesSchema";

export const charSheetDataSchema: JSONSchemaType<CharSheetData> = {
  type: "object",
  properties: {
    preset:       presetSchema,
    profile:      profileSchema,
    attributes:   attributesSchema,
    abilities:    abilitiesSchema,
    abilitiesExtension: abilitiesExtensionSchema,
    disciplines:  disciplinesSchema,
    backgrounds:  backgroundsSchema,
    virtues:      virtuesSchema,
    merits:       meritsSchema,
    flaws:        flawsSchema,
    state:        stateSchema,
    health:       healthSchema,
    healthChimerical: healthSchema,
    notes:        notesSchema,
    arts:         artsSchema,
    realms:       realmsSchema,
  },
  required: [
    "preset",
    "profile",
    "attributes",
    "abilities",
    "abilitiesExtension",
    "disciplines",
    "backgrounds",
    "virtues",
    "merits",
    "flaws",
    "state",
    "health",
    "healthChimerical",
    "notes",
    "arts",
    "realms",
  ],
  additionalProperties: false,
};
